### ISSUE TITLE
Is running adb commands from microcontroller possible?

### ISSUE THREAD

**Issue by kyrlon** [cstyan/adbDocumentation#14]
I recently posted a [question](https://android.stackexchange.com/q/252199/371737) on Android Stack Exchange, and while researching a possible solution, I came across this GitHub repository. My question is whether it is feasible to execute simple adb shell commands on an Android device from a microcontroller. To provide a simple example, I am interested in running the `adb reboot` command periodically as a simple task in a loop for an old android tablet that freezes sometimes.

Thank you for your attention and assistance!

**Comment by cstyan** [comment]
@kyrlon unfortunately I have no idea and suspect the answer is probably no. When I wrote this additional documentation I only tested commands via USB as that was the use case we cared about, we only needed to interact with devices from a Linux host.

> NOTE: The majority of the information presented is for use of the ADB protocol with USB. If you have information about it's use with TCP please submit a pull request.

**Comment by kyrlon** [comment]
@cstyan Thank you for your response! I am in no way an expert in this protocol so this will take some time to adapt and learn if I would go about the TCP route. I have a weak/lazy solution for my means with a Rpi zero in the meantime, but this would be neat if it is possible to do such commands on the lower level.

Again thanks alot for this well explored topic! The details given is much appreciated.
