### ISSUE TITLE
list (adb ls) size is not always 4 bytes???

### ISSUE THREAD

**Issue by metalex201** [cstyan/adbDocumentation#15]
![image](https://github.com/cstyan/adbDocumentation/assets/79465618/0792c01d-62ce-4218-9a81-8fd144d05358)
I'm trying to create an android library (for kotlin) that has every adb functionality i could get working, and i realised that files over 4 gigs wont fit into the size int limit of 4 bytes and for some reason it doesnt seem to appear to be any indication in a packet that it would be over the limit and i tried looking at packets and i couldnt find the last bit 
for example heres a result from adb ls with a 4.95gb file
000081a4 1270e1b11 65f76bf2 test.zip
the packet that is returned when i do a list and get the dent for this specific file 
a4810000111b0e27f26bf76508000000
Dent -> 44454e54
filetype -> a4810000 (big endian : 000081a4 as in the result from adb ls)
size -> 111b0e27 (MISSING THE LAST BIT -> 1)

test zip is 1270e1b11 (from adb ls result) little endian version is 111b0e271 <- extra bit here that is nowhere to be found in the packet.

Am i'm missing something here? or maybe i'm reading the packets in an incorrect way?

**Comment by metalex201** [comment]
i found a solution, from reading packets with wireshark through a an adb tcp connection i saw that instead of sending LIST as the command instead it sends LIS2 which then shows the packet in 8 bit formats instead of just 4 so this solves my issue, this should be mentioned in the docs!

**Comment by metalex201** [comment]
> i found a solution, from reading packets with wireshark through a an adb tcp connection i saw that instead of sending LIST as the command instead it sends LIS2 which then shows the packet in 8 bit formats instead of just 4 so this solves my issue, this should be mentioned in the docs!

and now dent is DNT2 too, this protocol is such a mess!

**Comment by cstyan** [comment]
It's been nearly 10 years since I worked with ADB and wrote these docs, so there very would could be many changes or additions to the protocol since then. PRs to add additional examples here are welcome :+1:

**Comment by metalex201** [comment]
> It's been nearly 10 years since I worked with ADB and wrote these docs, so there very would could be many changes or additions to the protocol since then. PRs to add additional examples here are welcome 👍

the last commit on the git repository for adb was apparently 7 years ago, i think this was just a quick fix for the size issue that never got written in the adb doccumentation. 

I'm gonna make PR once i figure out the exact differences between LIST and LIS2

**Comment by cstyan** [comment]
I haven't personally used ADB at all, especially not in the context I was when I wrote the documentation here, since at least  early 2016.

> I'm gonna make PR once i figure out the exact differences between LIST and LIS2

:+1: Glad to hear that, thank you.

**Comment by metalex201** [comment]
> I haven't personally used ADB at all, especially not in the context I was when I wrote the documentation here, since at least early 2016.
> 
> > I'm gonna make PR once i figure out the exact differences between LIST and LIS2
> 
> 👍 Glad to hear that, thank you.

I made a PR, hope its good enough for the doccumentation format.
